/**
* @file comm_struct_struct.h
* @brief auto generated by comm_struct.proto
* @author fergus <zfengzhen@gmail.com>
* @date 2015-07-14 16:08:40
*/


#pragma once


using namespace ProtoComm::Player;


#include <comm_struct.pb.h>
#include <string.h>


#define EQUIP_INFO_REPEATED_MAX_SIZE 100
#define SKILL_INFO_REPEATED_MAX_SIZE 100
#define NAME_STRING_MAX_SIZE 32
#define HERO_INFO_REPEATED_MAX_SIZE 100


typedef struct EquipInfo_struct {
	uint32_t id; // 装备ID
	int32_t level; //  装备等级
	int32_t exp; //  装备在该等级下的经验
} EquipInfoStruct;


typedef struct SkillInfo_struct {
	uint32_t id; //  技能ID
} SkillInfoStruct;


typedef struct HeroInfo_struct {
	uint32_t id; //  武将ID
	int32_t level; //  武将等级
	int32_t quality; //  武将阶数
	int32_t star; //  武将星数
	EquipInfoStruct equip_info[EQUIP_INFO_REPEATED_MAX_SIZE]; //  装备
	SkillInfoStruct skill_info[SKILL_INFO_REPEATED_MAX_SIZE]; //  武将技能
	int32_t exp; //  武将经验
} HeroInfoStruct;


typedef struct RoleInfo_struct {
	int32_t money; //  金币
	int32_t diamond; //  钻石
	int32_t level; //  召唤师等级
	char name[NAME_STRING_MAX_SIZE];
} RoleInfoStruct;


//  玩家数据
typedef struct PlayerData_struct {
	RoleInfoStruct role_info; //  召唤师相关属性
	HeroInfoStruct hero_info[HERO_INFO_REPEATED_MAX_SIZE]; //  武将
} PlayerDataStruct;


void ConvPrimitiveStructToProto(EquipInfoStruct* sct, EquipInfo* proto)
{
	proto->set_id(sct->id);
	proto->set_level(sct->level);
	proto->set_exp(sct->exp);
}


void ConvPrimitiveStructToProto(SkillInfoStruct* sct, SkillInfo* proto)
{
	proto->set_id(sct->id);
}


void ConvPrimitiveStructToProto(HeroInfoStruct* sct, HeroInfo* proto)
{
	proto->set_id(sct->id);
	proto->set_level(sct->level);
	proto->set_quality(sct->quality);
	proto->set_star(sct->star);
	proto->set_exp(sct->exp);
}


void ConvPrimitiveStructToProto(RoleInfoStruct* sct, RoleInfo* proto)
{
	proto->set_money(sct->money);
	proto->set_diamond(sct->diamond);
	proto->set_level(sct->level);
	proto->set_name(sct->name);
}


void ConvPrimitiveProtoToStruct(EquipInfo* proto, EquipInfoStruct* sct)
{
	sct->id = proto->id();
	sct->level = proto->level();
	sct->exp = proto->exp();
}


void ConvPrimitiveProtoToStruct(SkillInfo* proto, SkillInfoStruct* sct)
{
	sct->id = proto->id();
}


void ConvPrimitiveProtoToStruct(HeroInfo* proto, HeroInfoStruct* sct)
{
	sct->id = proto->id();
	sct->level = proto->level();
	sct->quality = proto->quality();
	sct->star = proto->star();
	sct->exp = proto->exp();
}


void ConvPrimitiveProtoToStruct(RoleInfo* proto, RoleInfoStruct* sct)
{
	sct->money = proto->money();
	sct->diamond = proto->diamond();
	sct->level = proto->level();
	strncpy(sct->name, proto->name().c_str(), NAME_STRING_MAX_SIZE);
}


